import type {
  ColumnDataType,
  ColumnMetadata,
  DatabaseType,
  TableMetadata,
  WhereClause,
  WhereCondition,
} from "../types";

/**
 * Resolve the database name from a dialect string or provider configuration.
 *
 * @param {DatabaseType | string} [dialect] - Database dialect or provider configuration
 * @returns {string} Normalized database dialect name
 */
export function dialectName(dialect?: DatabaseType | string): string {
  if (!dialect) {
    return "mysql";
  }
  return typeof dialect === "string" ? dialect : dialect.name;
}

/**
 * Quote an SQL identifier using the quoting rules for a dialect.
 *
 * @param {string} identifier - Table, column, or index identifier
 * @param {DatabaseType | string} [dialect] - Database dialect or provider configuration
 * @returns {string} Safely quoted SQL identifier
 */
export function quoteIdentifier(identifier: string, dialect?: DatabaseType | string): string {
  const name = dialectName(dialect);
  if (name === "postgres") {
    return `"${identifier.replaceAll('"', '""')}"`;
  }
  return `\`${identifier.replaceAll("`", "``")}\``;
}

/**
 * Create a parameter placeholder using the dialect's parameter syntax.
 *
 * @param {number} index - One-based parameter index
 * @param {DatabaseType | string} [dialect] - Database dialect or provider configuration
 * @returns {string} Dialect-specific placeholder (`?` or `$n`)
 */
export function placeholder(index: number, dialect?: DatabaseType | string): string {
  return dialectName(dialect) === "postgres" ? `$${index}` : "?";
}

/**
 * Append a parameter and return its dialect-specific placeholder.
 *
 * @param {unknown[]} params - Parameter array that receives the value
 * @param {unknown} value - Value to bind
 * @param {DatabaseType | string} [dialect] - Database dialect or provider configuration
 * @returns {string} Placeholder referencing the appended parameter
 */
function addParam(params: unknown[], value: unknown, dialect?: DatabaseType | string): string {
  params.push(value);
  return placeholder(params.length, dialect);
}

/**
 * Compile column type to SQL string for a specific database dialect
 * @param {ColumnMetadata} col - Column metadata
 * @param {DatabaseType} dialect - Database dialect
 * @returns {string} SQL column type string
 */
export function compileColumnType(col: ColumnMetadata, dialect: DatabaseType): string {
  const name = dialectName(dialect);

  const typeMap: Record<ColumnDataType, Record<string, string>> = {
    integer: {
      mysql: "INT",
      mariadb: "INT",
      sqlite: "INTEGER",
      postgres: "INTEGER",
      file: "INTEGER",
    },
    bigint: {
      mysql: "BIGINT",
      mariadb: "BIGINT",
      sqlite: "INTEGER",
      postgres: "BIGINT",
      file: "BIGINT",
    },
    varchar: {
      mysql: `VARCHAR(${col.length ?? 255})`,
      mariadb: `VARCHAR(${col.length ?? 255})`,
      sqlite: "TEXT",
      postgres: `VARCHAR(${col.length ?? 255})`,
      file: "VARCHAR",
    },
    char: {
      mysql: `CHAR(${col.length ?? 1})`,
      mariadb: `CHAR(${col.length ?? 1})`,
      sqlite: "TEXT",
      postgres: `CHAR(${col.length ?? 1})`,
      file: "CHAR",
    },
    text: { mysql: "TEXT", mariadb: "TEXT", sqlite: "TEXT", postgres: "TEXT", file: "TEXT" },
    boolean: {
      mysql: "TINYINT(1)",
      mariadb: "TINYINT(1)",
      sqlite: "INTEGER",
      postgres: "BOOLEAN",
      file: "BOOLEAN",
    },
    json: { mysql: "JSON", mariadb: "JSON", sqlite: "TEXT", postgres: "JSONB", file: "JSON" },
    array: { mysql: "JSON", mariadb: "JSON", sqlite: "TEXT", postgres: "JSONB", file: "JSON" },
    datetime: {
      mysql: "DATETIME",
      mariadb: "DATETIME",
      sqlite: "TEXT",
      postgres: "TIMESTAMP",
      file: "DATETIME",
    },
    timestamp: {
      mysql: "TIMESTAMP",
      mariadb: "TIMESTAMP",
      sqlite: "TEXT",
      postgres: "TIMESTAMP",
      file: "TIMESTAMP",
    },
    decimal: {
      mysql: `DECIMAL(${col.precision ?? 10},${col.scale ?? 2})`,
      mariadb: `DECIMAL(${col.precision ?? 10},${col.scale ?? 2})`,
      sqlite: "REAL",
      postgres: `DECIMAL(${col.precision ?? 10},${col.scale ?? 2})`,
      file: "DECIMAL",
    },
    float: { mysql: "FLOAT", mariadb: "FLOAT", sqlite: "REAL", postgres: "REAL", file: "FLOAT" },
    blob: { mysql: "BLOB", mariadb: "BLOB", sqlite: "BLOB", postgres: "BYTEA", file: "BLOB" },
  };

  return typeMap[col.type]?.[name] ?? "TEXT";
}

/**
 * Compile a column definition to a SQL fragment
 * @param {ColumnMetadata} col - Column metadata
 * @param {DatabaseType} dialect - Database dialect
 * @returns {string} SQL column definition
 */
export function compileColumnDef(col: ColumnMetadata, dialect: DatabaseType): string {
  const name = dialectName(dialect);
  const parts: string[] = [quoteIdentifier(col.name, dialect), compileColumnType(col, dialect)];

  if (col.primaryKey) {
    parts.push("PRIMARY KEY");
  }
  if (col.autoIncrement) {
    if (name === "postgres") {
      parts.push("GENERATED BY DEFAULT AS IDENTITY");
    } else if (name === "mysql" || name === "mariadb") {
      parts.push("AUTO_INCREMENT");
    } else {
      parts.push("AUTOINCREMENT");
    }
  }
  if (col.notNull && !col.primaryKey) {
    parts.push("NOT NULL");
  }
  if (col.unique && !col.primaryKey) {
    parts.push("UNIQUE");
  }
  if (col.defaultValue !== undefined) {
    if (typeof col.defaultValue === "string") {
      parts.push(`DEFAULT '${col.defaultValue.replaceAll("'", "''")}'`);
    } else if (col.defaultValue === null) {
      parts.push("DEFAULT NULL");
    } else if (col.defaultValue instanceof Date) {
      parts.push(`DEFAULT '${col.defaultValue.toISOString()}'`);
    } else {
      parts.push(`DEFAULT ${col.defaultValue}`);
    }
  }

  return parts.join(" ");
}

/**
 * Compile a CREATE TABLE statement from table metadata
 * @param {TableMetadata} table - Table metadata
 * @param {DatabaseType} dialect - Database dialect
 * @returns {string} CREATE TABLE SQL statement
 */
export function compileCreateTable(table: TableMetadata, dialect: DatabaseType): string {
  const columnDefs: string[] = [];
  const constraints: string[] = [];

  for (const col of table.columns) {
    columnDefs.push(compileColumnDef(col, dialect));

    if (col.references) {
      const onDelete = col.references.onDelete ? ` ON DELETE ${col.references.onDelete}` : "";
      const onUpdate = col.references.onUpdate ? ` ON UPDATE ${col.references.onUpdate}` : "";
      constraints.push(
        `FOREIGN KEY (${quoteIdentifier(col.name, dialect)}) REFERENCES ${quoteIdentifier(col.references.table, dialect)}(${quoteIdentifier(col.references.column, dialect)})${onDelete}${onUpdate}`,
      );
    }
  }

  const allDefs = [...columnDefs, ...constraints].join(", ");
  return `CREATE TABLE IF NOT EXISTS ${quoteIdentifier(table.name, dialect)} (${allDefs})`;
}

/**
 * Compile a WHERE clause from a condition object
 * @param {WhereClause} where - Where clause object
 * @param {unknown[]} params - Parameter array to push values into
 * @param {string} [dialect] - Database dialect
 * @returns {string} SQL WHERE fragment
 */
export function compileWhere(
  where: WhereClause,
  params: unknown[],
  dialect?: DatabaseType | string,
): string {
  const conditions: string[] = [];

  for (const [key, value] of Object.entries(where)) {
    if (key === "OR" && Array.isArray(value)) {
      const orParts = (value as WhereClause[]).map((sub) => compileWhere(sub, params, dialect));
      if (orParts.length > 0) {
        conditions.push(`(${orParts.join(" OR ")})`);
      }
      continue;
    }
    if (key === "AND" && Array.isArray(value)) {
      const andParts = (value as WhereClause[]).map((sub) => compileWhere(sub, params, dialect));
      if (andParts.length > 0) {
        conditions.push(`(${andParts.join(" AND ")})`);
      }
      continue;
    }

    if (value !== null && typeof value === "object" && !Array.isArray(value)) {
      const cond = value as WhereCondition;
      const column = quoteIdentifier(key, dialect);
      if (cond.eq !== undefined) {
        conditions.push(`${column} = ${addParam(params, cond.eq, dialect)}`);
      }
      if (cond.neq !== undefined) {
        conditions.push(`${column} != ${addParam(params, cond.neq, dialect)}`);
      }
      if (cond.gt !== undefined) {
        conditions.push(`${column} > ${addParam(params, cond.gt, dialect)}`);
      }
      if (cond.gte !== undefined) {
        conditions.push(`${column} >= ${addParam(params, cond.gte, dialect)}`);
      }
      if (cond.lt !== undefined) {
        conditions.push(`${column} < ${addParam(params, cond.lt, dialect)}`);
      }
      if (cond.lte !== undefined) {
        conditions.push(`${column} <= ${addParam(params, cond.lte, dialect)}`);
      }
      if (cond.like !== undefined) {
        conditions.push(`${column} LIKE ${addParam(params, cond.like, dialect)}`);
      }
      if (cond.notLike !== undefined) {
        conditions.push(`${column} NOT LIKE ${addParam(params, cond.notLike, dialect)}`);
      }
      if (cond.in !== undefined && Array.isArray(cond.in)) {
        const placeholders = cond.in.map((value) => addParam(params, value, dialect)).join(", ");
        conditions.push(`${column} IN (${placeholders})`);
      }
      if (cond.notIn !== undefined && Array.isArray(cond.notIn)) {
        const placeholders = cond.notIn.map((value) => addParam(params, value, dialect)).join(", ");
        conditions.push(`${column} NOT IN (${placeholders})`);
      }
      if (cond.isNull === true) {
        conditions.push(`${column} IS NULL`);
      }
      if (cond.isNull === false) {
        conditions.push(`${column} IS NOT NULL`);
      }
      if (cond.between !== undefined && Array.isArray(cond.between)) {
        const start = addParam(params, cond.between[0], dialect);
        const end = addParam(params, cond.between[1], dialect);
        conditions.push(`${column} BETWEEN ${start} AND ${end}`);
      }
    } else {
      conditions.push(`${quoteIdentifier(key, dialect)} = ${addParam(params, value, dialect)}`);
    }
  }

  return conditions.length > 0 ? conditions.join(" AND ") : "1=1";
}

/**
 * Compile a SELECT query from options.
 *
 * @param {string} tableName - Table name
 * @param {object} options - Selection, filtering, ordering, and pagination options
 * @param {string[]} [options.select] - Columns to select
 * @param {WhereClause} [options.where] - Filtering conditions
 * @param {Record<string, "asc" | "desc">} [options.orderBy] - Sort order by column
 * @param {number} [options.take] - Maximum number of rows
 * @param {number} [options.skip] - Number of rows to skip
 * @param {unknown[]} params - Parameter array to receive bound values
 * @param {DatabaseType | string} [dialect] - Database dialect or provider configuration
 * @returns {string} Compiled SQL SELECT statement
 */
export function compileSelect(
  tableName: string,
  options: {
    select?: string[];
    where?: WhereClause;
    orderBy?: Record<string, "asc" | "desc">;
    take?: number;
    skip?: number;
  },
  params: unknown[],
  dialect?: DatabaseType | string,
): string {
  const cols = options.select?.map((c) => quoteIdentifier(String(c), dialect)).join(", ") ?? "*";
  let sql = `SELECT ${cols} FROM ${quoteIdentifier(tableName, dialect)}`;

  if (options.where && Object.keys(options.where).length > 0) {
    sql += ` WHERE ${compileWhere(options.where, params, dialect)}`;
  }
  if (options.orderBy) {
    const orderParts = Object.entries(options.orderBy).map(
      ([col, dir]) => `${quoteIdentifier(col, dialect)} ${dir.toUpperCase()}`,
    );
    if (orderParts.length > 0) {
      sql += ` ORDER BY ${orderParts.join(", ")}`;
    }
  }
  if (options.take !== undefined) {
    sql += ` LIMIT ${options.take}`;
  }
  if (options.skip !== undefined) {
    sql += ` OFFSET ${options.skip}`;
  }

  return sql;
}

/**
 * Compile an INSERT statement.
 *
 * @param {string} tableName - Table name
 * @param {Record<string, unknown>} data - Column values to insert
 * @param {unknown[]} params - Parameter array to receive bound values
 * @param {DatabaseType | string} [dialect] - Database dialect or provider configuration
 * @returns {string} Compiled SQL INSERT statement
 */
export function compileInsert(
  tableName: string,
  data: Record<string, unknown>,
  params: unknown[],
  dialect?: DatabaseType | string,
): string {
  const keys = Object.keys(data);
  const cols = keys.map((k) => quoteIdentifier(k, dialect)).join(", ");
  const placeholders = keys.map((key) => addParam(params, data[key], dialect)).join(", ");
  return `INSERT INTO ${quoteIdentifier(tableName, dialect)} (${cols}) VALUES (${placeholders})`;
}

/**
 * Compile a bulk INSERT statement for multiple rows.
 *
 * @param {string} tableName - Table name
 * @param {Record<string, unknown>[]} data - Rows to insert; all rows use the first row's columns
 * @param {unknown[]} params - Parameter array to receive bound values
 * @param {DatabaseType | string} [dialect] - Database dialect or provider configuration
 * @returns {string} Compiled SQL bulk INSERT statement, or an empty string for no rows
 */
export function compileBulkInsert(
  tableName: string,
  data: Record<string, unknown>[],
  params: unknown[],
  dialect?: DatabaseType | string,
): string {
  if (data.length === 0) {
    return "";
  }
  const keys = Object.keys(data[0]!);
  const cols = keys.map((k) => quoteIdentifier(k, dialect)).join(", ");
  const valuePlaceholders = data
    .map((row) => `(${keys.map((key) => addParam(params, row[key], dialect)).join(", ")})`)
    .join(", ");

  return `INSERT INTO ${quoteIdentifier(tableName, dialect)} (${cols}) VALUES ${valuePlaceholders}`;
}

/**
 * Compile an UPDATE statement.
 *
 * @param {string} tableName - Table name
 * @param {Record<string, unknown>} data - Column values to update
 * @param {WhereClause} where - Conditions identifying rows to update
 * @param {unknown[]} params - Parameter array to receive bound values
 * @param {DatabaseType | string} [dialect] - Database dialect or provider configuration
 * @returns {string} Compiled SQL UPDATE statement
 */
export function compileUpdate(
  tableName: string,
  data: Record<string, unknown>,
  where: WhereClause,
  params: unknown[],
  dialect?: DatabaseType | string,
): string {
  const setParts = Object.keys(data).map(
    (key) => `${quoteIdentifier(key, dialect)} = ${addParam(params, data[key], dialect)}`,
  );
  let sql = `UPDATE ${quoteIdentifier(tableName, dialect)} SET ${setParts.join(", ")}`;
  if (Object.keys(where).length > 0) {
    sql += ` WHERE ${compileWhere(where, params, dialect)}`;
  }
  return sql;
}

/**
 * Compile a DELETE statement.
 *
 * @param {string} tableName - Table name
 * @param {WhereClause} where - Conditions identifying rows to delete
 * @param {unknown[]} params - Parameter array to receive bound values
 * @param {DatabaseType | string} [dialect] - Database dialect or provider configuration
 * @returns {string} Compiled SQL DELETE statement
 */
export function compileDelete(
  tableName: string,
  where: WhereClause,
  params: unknown[],
  dialect?: DatabaseType | string,
): string {
  let sql = `DELETE FROM ${quoteIdentifier(tableName, dialect)}`;
  if (Object.keys(where).length > 0) {
    sql += ` WHERE ${compileWhere(where, params, dialect)}`;
  }
  return sql;
}
