import type {
  ColumnDataType,
  ColumnMetadata,
  DatabaseType,
  TableMetadata,
  WhereClause,
  WhereCondition,
} from "../types";

/**
 * Compile column type to SQL string for a specific database dialect
 * @param {ColumnMetadata} col - Column metadata
 * @param {DatabaseType} dialect - Database dialect
 * @returns {string} SQL column type string
 */
export function compileColumnType(col: ColumnMetadata, dialect: DatabaseType): string {
  const name = typeof dialect === "string" ? dialect : dialect.name;

  const typeMap: Record<ColumnDataType, Record<string, string>> = {
    integer: {
      mysql: "INT",
      mariadb: "INT",
      sqlite: "INTEGER",
      postgres: "INTEGER",
      file: "INTEGER",
    },
    bigint: {
      mysql: "BIGINT",
      mariadb: "BIGINT",
      sqlite: "INTEGER",
      postgres: "BIGINT",
      file: "BIGINT",
    },
    varchar: {
      mysql: `VARCHAR(${col.length ?? 255})`,
      mariadb: `VARCHAR(${col.length ?? 255})`,
      sqlite: "TEXT",
      postgres: `VARCHAR(${col.length ?? 255})`,
      file: "VARCHAR",
    },
    char: {
      mysql: `CHAR(${col.length ?? 1})`,
      mariadb: `CHAR(${col.length ?? 1})`,
      sqlite: "TEXT",
      postgres: `CHAR(${col.length ?? 1})`,
      file: "CHAR",
    },
    text: { mysql: "TEXT", mariadb: "TEXT", sqlite: "TEXT", postgres: "TEXT", file: "TEXT" },
    boolean: {
      mysql: "TINYINT(1)",
      mariadb: "TINYINT(1)",
      sqlite: "INTEGER",
      postgres: "BOOLEAN",
      file: "BOOLEAN",
    },
    json: { mysql: "JSON", mariadb: "JSON", sqlite: "TEXT", postgres: "JSONB", file: "JSON" },
    array: { mysql: "JSON", mariadb: "JSON", sqlite: "TEXT", postgres: "JSONB", file: "JSON" },
    datetime: {
      mysql: "DATETIME",
      mariadb: "DATETIME",
      sqlite: "TEXT",
      postgres: "TIMESTAMP",
      file: "DATETIME",
    },
    timestamp: {
      mysql: "TIMESTAMP",
      mariadb: "TIMESTAMP",
      sqlite: "TEXT",
      postgres: "TIMESTAMP",
      file: "TIMESTAMP",
    },
    decimal: {
      mysql: `DECIMAL(${col.precision ?? 10},${col.scale ?? 2})`,
      mariadb: `DECIMAL(${col.precision ?? 10},${col.scale ?? 2})`,
      sqlite: "REAL",
      postgres: `DECIMAL(${col.precision ?? 10},${col.scale ?? 2})`,
      file: "DECIMAL",
    },
    float: { mysql: "FLOAT", mariadb: "FLOAT", sqlite: "REAL", postgres: "REAL", file: "FLOAT" },
    blob: { mysql: "BLOB", mariadb: "BLOB", sqlite: "BLOB", postgres: "BYTEA", file: "BLOB" },
  };

  return typeMap[col.type]?.[name] ?? "TEXT";
}

/**
 * Compile a column definition to a SQL fragment
 * @param {ColumnMetadata} col - Column metadata
 * @param {DatabaseType} dialect - Database dialect
 * @returns {string} SQL column definition
 */
export function compileColumnDef(col: ColumnMetadata, dialect: DatabaseType): string {
  const name = typeof dialect === "string" ? dialect : dialect.name;
  const quote = (s: string) => (name === "postgres" ? `"${s}"` : `\`${s}\``);
  const parts: string[] = [quote(col.name), compileColumnType(col, dialect)];

  if (col.primaryKey) {
    parts.push("PRIMARY KEY");
  }
  if (col.autoIncrement) {
    if (name === "postgres") {
      parts.push("GENERATED BY DEFAULT AS IDENTITY");
    } else if (name === "mysql" || name === "mariadb") {
      parts.push("AUTO_INCREMENT");
    } else {
      parts.push("AUTOINCREMENT");
    }
  }
  if (col.notNull && !col.primaryKey) {
    parts.push("NOT NULL");
  }
  if (col.unique && !col.primaryKey) {
    parts.push("UNIQUE");
  }
  if (col.defaultValue !== undefined) {
    if (typeof col.defaultValue === "string") {
      parts.push(`DEFAULT '${col.defaultValue}'`);
    } else if (col.defaultValue === null) {
      parts.push("DEFAULT NULL");
    } else if (col.defaultValue instanceof Date) {
      parts.push(`DEFAULT '${col.defaultValue.toISOString()}'`);
    } else {
      parts.push(`DEFAULT ${col.defaultValue}`);
    }
  }

  return parts.join(" ");
}

/**
 * Compile a CREATE TABLE statement from table metadata
 * @param {TableMetadata} table - Table metadata
 * @param {DatabaseType} dialect - Database dialect
 * @returns {string} CREATE TABLE SQL statement
 */
export function compileCreateTable(table: TableMetadata, dialect: DatabaseType): string {
  const name = typeof dialect === "string" ? dialect : dialect.name;
  const quote = (s: string) => (name === "postgres" ? `"${s}"` : `\`${s}\``);
  const columnDefs: string[] = [];
  const constraints: string[] = [];

  for (const col of table.columns) {
    columnDefs.push(compileColumnDef(col, dialect));

    if (col.references) {
      const onDelete = col.references.onDelete ? ` ON DELETE ${col.references.onDelete}` : "";
      const onUpdate = col.references.onUpdate ? ` ON UPDATE ${col.references.onUpdate}` : "";
      constraints.push(
        `FOREIGN KEY (${quote(col.name)}) REFERENCES ${quote(col.references.table)}(${quote(col.references.column)})${onDelete}${onUpdate}`,
      );
    }
  }

  const allDefs = [...columnDefs, ...constraints].join(", ");
  return `CREATE TABLE IF NOT EXISTS ${quote(table.name)} (${allDefs})`;
}

/**
 * Compile a WHERE clause from a condition object
 * @param {WhereClause} where - Where clause object
 * @param {unknown[]} params - Parameter array to push values into
 * @param {string} [dialect] - Database dialect
 * @returns {string} SQL WHERE fragment
 */
export function compileWhere(where: WhereClause, params: unknown[], dialect?: string): string {
  const quote = (s: string) => (dialect === "postgres" ? `"${s}"` : `\`${s}\``);
  const conditions: string[] = [];

  for (const [key, value] of Object.entries(where)) {
    if (key === "OR" && Array.isArray(value)) {
      const orParts = (value as WhereClause[]).map((sub) => compileWhere(sub, params, dialect));
      if (orParts.length > 0) {
        conditions.push(`(${orParts.join(" OR ")})`);
      }
      continue;
    }
    if (key === "AND" && Array.isArray(value)) {
      const andParts = (value as WhereClause[]).map((sub) => compileWhere(sub, params, dialect));
      if (andParts.length > 0) {
        conditions.push(`(${andParts.join(" AND ")})`);
      }
      continue;
    }

    if (value !== null && typeof value === "object" && !Array.isArray(value)) {
      const cond = value as WhereCondition;
      if (cond.eq !== undefined) {
        params.push(cond.eq);
        conditions.push(`${quote(key)} = ?`);
      }
      if (cond.neq !== undefined) {
        params.push(cond.neq);
        conditions.push(`${quote(key)} != ?`);
      }
      if (cond.gt !== undefined) {
        params.push(cond.gt);
        conditions.push(`${quote(key)} > ?`);
      }
      if (cond.gte !== undefined) {
        params.push(cond.gte);
        conditions.push(`${quote(key)} >= ?`);
      }
      if (cond.lt !== undefined) {
        params.push(cond.lt);
        conditions.push(`${quote(key)} < ?`);
      }
      if (cond.lte !== undefined) {
        params.push(cond.lte);
        conditions.push(`${quote(key)} <= ?`);
      }
      if (cond.like !== undefined) {
        params.push(cond.like);
        conditions.push(`${quote(key)} LIKE ?`);
      }
      if (cond.notLike !== undefined) {
        params.push(cond.notLike);
        conditions.push(`${quote(key)} NOT LIKE ?`);
      }
      if (cond.in !== undefined && Array.isArray(cond.in)) {
        const placeholders = cond.in.map(() => "?").join(", ");
        params.push(...cond.in);
        conditions.push(`${quote(key)} IN (${placeholders})`);
      }
      if (cond.notIn !== undefined && Array.isArray(cond.notIn)) {
        const placeholders = cond.notIn.map(() => "?").join(", ");
        params.push(...cond.notIn);
        conditions.push(`${quote(key)} NOT IN (${placeholders})`);
      }
      if (cond.isNull === true) {
        conditions.push(`${quote(key)} IS NULL`);
      }
      if (cond.isNull === false) {
        conditions.push(`${quote(key)} IS NOT NULL`);
      }
      if (cond.between !== undefined && Array.isArray(cond.between)) {
        params.push(cond.between[0], cond.between[1]);
        conditions.push(`${quote(key)} BETWEEN ? AND ?`);
      }
    } else {
      params.push(value);
      conditions.push(`${quote(key)} = ?`);
    }
  }

  return conditions.length > 0 ? conditions.join(" AND ") : "1=1";
}

/**
 * Compile a SELECT query from options
 * @param {string} tableName - Table name
 * @param {object} options - Query options
 * @param {unknown[]} params - Parameter array
 * @param {string} [dialect] - Database dialect
 * @returns {string} SQL SELECT statement
 */
export function compileSelect(
  tableName: string,
  options: {
    select?: string[];
    where?: WhereClause;
    orderBy?: Record<string, "asc" | "desc">;
    take?: number;
    skip?: number;
  },
  params: unknown[],
  dialect?: string,
): string {
  const quote = (s: string) => (dialect === "postgres" ? `"${s}"` : `\`${s}\``);
  const cols = options.select?.map((c) => quote(String(c))).join(", ") ?? "*";
  let sql = `SELECT ${cols} FROM ${quote(tableName)}`;

  if (options.where && Object.keys(options.where).length > 0) {
    sql += ` WHERE ${compileWhere(options.where, params, dialect)}`;
  }
  if (options.orderBy) {
    const orderParts = Object.entries(options.orderBy).map(
      ([col, dir]) => `${quote(col)} ${dir.toUpperCase()}`,
    );
    if (orderParts.length > 0) {
      sql += ` ORDER BY ${orderParts.join(", ")}`;
    }
  }
  if (options.take !== undefined) {
    sql += ` LIMIT ${options.take}`;
  }
  if (options.skip !== undefined) {
    sql += ` OFFSET ${options.skip}`;
  }

  return sql;
}

/**
 * Compile an INSERT statement
 * @param {string} tableName - Table name
 * @param {Record<string, unknown>} data - Data to insert
 * @param {unknown[]} params - Parameter array
 * @param {string} [dialect] - Database dialect
 * @returns {string} SQL INSERT statement
 */
export function compileInsert(
  tableName: string,
  data: Record<string, unknown>,
  params: unknown[],
  dialect?: string,
): string {
  const quote = (s: string) => (dialect === "postgres" ? `"${s}"` : `\`${s}\``);
  const keys = Object.keys(data);
  const cols = keys.map((k) => quote(k)).join(", ");
  const placeholders = keys.map(() => "?").join(", ");
  params.push(...keys.map((k) => data[k]));
  return `INSERT INTO ${quote(tableName)} (${cols}) VALUES (${placeholders})`;
}

/**
 * Compile a bulk INSERT statement for multiple rows
 * @param {string} tableName - Table name
 * @param {Record<string, unknown>[]} data - Array of data to insert
 * @param {unknown[]} params - Parameter array
 * @param {string} [dialect] - Database dialect
 * @returns {string} SQL bulk INSERT statement
 */
export function compileBulkInsert(
  tableName: string,
  data: Record<string, unknown>[],
  params: unknown[],
  dialect?: string,
): string {
  if (data.length === 0) {
    return "";
  }
  const quote = (s: string) => (dialect === "postgres" ? `"${s}"` : `\`${s}\``);
  const keys = Object.keys(data[0]!);
  const cols = keys.map((k) => quote(k)).join(", ");
  const valuePlaceholders = data.map(() => `(${keys.map(() => "?").join(", ")})`).join(", ");

  for (const row of data) {
    for (const key of keys) {
      params.push(row[key]);
    }
  }

  return `INSERT INTO ${quote(tableName)} (${cols}) VALUES ${valuePlaceholders}`;
}

/**
 * Compile an UPDATE statement
 * @param {string} tableName - Table name
 * @param {Record<string, unknown>} data - Data to update
 * @param {WhereClause} where - Where clause
 * @param {unknown[]} params - Parameter array
 * @param {string} [dialect] - Database dialect
 * @returns {string} SQL UPDATE statement
 */
export function compileUpdate(
  tableName: string,
  data: Record<string, unknown>,
  where: WhereClause,
  params: unknown[],
  dialect?: string,
): string {
  const quote = (s: string) => (dialect === "postgres" ? `"${s}"` : `\`${s}\``);
  const setParts = Object.keys(data).map((k) => {
    params.push(data[k]);
    return `${quote(k)} = ?`;
  });
  let sql = `UPDATE ${quote(tableName)} SET ${setParts.join(", ")}`;
  if (Object.keys(where).length > 0) {
    sql += ` WHERE ${compileWhere(where, params, dialect)}`;
  }
  return sql;
}

/**
 * Compile a DELETE statement
 * @param {string} tableName - Table name
 * @param {WhereClause} where - Where clause
 * @param {unknown[]} params - Parameter array
 * @param {string} [dialect] - Database dialect
 * @returns {string} SQL DELETE statement
 */
export function compileDelete(
  tableName: string,
  where: WhereClause,
  params: unknown[],
  dialect?: string,
): string {
  const quote = (s: string) => (dialect === "postgres" ? `"${s}"` : `\`${s}\``);
  let sql = `DELETE FROM ${quote(tableName)}`;
  if (Object.keys(where).length > 0) {
    sql += ` WHERE ${compileWhere(where, params, dialect)}`;
  }
  return sql;
}
