name: Continuous Integration

on:
  push:
    branches:
      - master
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  testing:
    runs-on: self-hosted
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm run lint
      - name: Build
        run: pnpm run build
      - name: Test (Bun)
        run: bun run test
      - name: Test (Node)
        run: npm test
      - name: Test Summary
        if: always()
        run: bun Actions/summary.js
